version: '2'
services:
  rabbitmq:
    image: andrewkeig/rabbitmq-mqtt-enabled
    ports:
      - "15672:15672"
      - "5672:5672"
      - "1883:1883"
  db:
    image: postgres
    ports:
      - "5432:5432"
